project:
  type: website
  output-dir: docs

website:
  title: Zoey
  navbar:
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - text: "临床编程"
        href: knowledge_base.qmd       
      - text: "R语言"
        href: r/R.qmd
        
  sidebar:
    - title: "R"
      style: "docked"
      background: light
      contents:
        - section: "R基础"
          contents:
            - r/R.qmd
            - r/R1.qmd
        - section: "tidyverse"
          href: r/tidyverse.qmd
          contents:
            - r/tidyverse.qmd
        - section: "画图"
          href: r/visnetwork.qmd
          contents:
            - r/visnetwork.qmd
    - title: "实体瘤"
      style: "docked"
      background: light
      contents:
        - section: "实体瘤"
          href: oncology/oncology.qmd
          contents:
            - oncology/oncology.qmd
            - oncology/pfs.qmd
            - oncology/adtr.qmd
            - oncology/adrs.qmd
            - oncology/addates.qmd
            - oncology/adtte.qmd
            - oncology/statistics.qmd
    - title: "药物暴露"
      style: "docked"
      background: light
      contents:
        - section: "药物暴露"
          href: ex/ex.qmd
          contents:
            - ex/ex.qmd
    - title: "药代动力学"
      style: "docked"
      background: light
      contents:
        - section: "药代动力学"
          href: pk/pk.qmd
          contents:
            - pk/pk.qmd
            
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: source

