project:
  type: website
  output-dir: docs

website:
  title: Zoey
  navbar:
    search: true
    left:
      - text: "首页"
        href: index.qmd
      - text: "临床编程"
        href: clinical-programming.qmd       
      - text: "R语言"
        href: r-programming.qmd
        
  sidebar:
    - title: "R语言"
      style: "docked"
      background: light
      contents:
        - section: "数据处理"
          contents:
            - r/transform.qmd
        #     - r/R1.qmd
        # - section: "tidyverse"
        #   href: r/tidyverse.qmd
        #   contents:
        #     - r/tidyverse.qmd
        # - section: "画图-ggplot2"
        #   href: r/barplot.qmd
        #   contents:
        #     - r/barplot.qmd
    - title: "肿瘤"
      style: "docked"
      background: light
      contents:
        - section: "实体瘤"
          href: oncology/oncology.qmd
          contents:
            - oncology/oncology.qmd
            - oncology/pfs.qmd
            - oncology/adtr.qmd
            - oncology/adrs.qmd
            - oncology/addates.qmd
            - oncology/adtte.qmd
            - oncology/statistics.qmd
        - section: "前列腺癌"
          href: oncology/prostate_cancer.qmd
    - title: "药物暴露"
      style: "docked"
      background: light
      contents:
        - section: "药物暴露"
          href: ex/ex.qmd
          contents:
            - ex/ex.qmd
    - title: "药代动力学"
      style: "docked"
      background: light
      contents:
        - section: "药代动力学"
          href: pk/pk.qmd
          contents:
            - pk/pk.qmd
    - title: "法规"
      style: "docked"
      background: light
      contents:
        - section: "法规"
          href: rules/dipp.qmd
          contents:
            - rules/dipp.qmd
            
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: source

