---
title: "ADTR"
---

# 1 ADTR

ADTR数据集存放病灶信息，如靶病灶径长、靶病灶直径和、非靶病状态、是否有新病灶等。在出瀑布图时会被用到。

## 1.1 ADTR包含的变量

+----------------------------------------+-----------------------------------------------------------------------------------------------------------------+
| 变量名                                 | 描述                                                                                                            |
+========================================+=================================================================================================================+
| USUBJID、ASEQ、TRGRPID、TRLNKID、TULOC |                                                                                                                 |
+----------------------------------------+-----------------------------------------------------------------------------------------------------------------+
| PARAM、PARAMCD                         | LDIAM-最长径，LPERP-最短径，TUMSTATE-肿瘤状态，DIAMETER-直径，ASUMDIAM-分析用靶病灶直径总和，SUMDIAM-直径总和。 |
|                                        |                                                                                                                 |
|                                        | 按照USUBJID+TREVAL+VISIT，输出一条分析用靶病灶直径和                                                            |
+----------------------------------------+-----------------------------------------------------------------------------------------------------------------+
| PARAMTYP                               | 当PARAMCD为ASUMDIAM时，PARAMTYP=衍生                                                                            |
+----------------------------------------+-----------------------------------------------------------------------------------------------------------------+
| PARCAT1                                | TRCAT(淋巴结、非淋巴结）                                                                                        |
+----------------------------------------+-----------------------------------------------------------------------------------------------------------------+
| AVAL、AVALC                            |                                                                                                                 |
+----------------------------------------+-----------------------------------------------------------------------------------------------------------------+
| BASE、BASEC                            |                                                                                                                 |
+----------------------------------------+-----------------------------------------------------------------------------------------------------------------+
| CHG                                    |                                                                                                                 |
+----------------------------------------+-----------------------------------------------------------------------------------------------------------------+
| PCHG                                   |                                                                                                                 |
+----------------------------------------+-----------------------------------------------------------------------------------------------------------------+
| TRDTC、ADT、ADY                        | ASUMDIAM的ADT为各访视靶病灶影像学检查日期的最大值                                                               |
+----------------------------------------+-----------------------------------------------------------------------------------------------------------------+
| VISIT、VISITNUM                        |                                                                                                                 |
+----------------------------------------+-----------------------------------------------------------------------------------------------------------------+
| ABLFL                                  | 首次给药前最后一次非空检测                                                                                      |
+----------------------------------------+-----------------------------------------------------------------------------------------------------------------+
| ANL01FL                                | 对于PARAMCD in ('SUMDIAM','ASUMDIAM')的记录，若发生在首次疾病进展和新抗肿瘤当天或之前，则赋值'是'               |
+----------------------------------------+-----------------------------------------------------------------------------------------------------------------+
| ANL02FL                                | 对于PARAMCD in ('SUMDIAM','ASUMDIAM')的记录，若该条记录对应的靶病灶评估结果有效，则赋值'是'                     |
+----------------------------------------+-----------------------------------------------------------------------------------------------------------------+
| ANL03FL                                | 对于PARAMCD in ('SUMDIAM','ASUMDIAM')且ANL01FL和ANL02FL为'是'的记录，选择基线后最早出现的最小PCHG值。           |
+----------------------------------------+-----------------------------------------------------------------------------------------------------------------+
| TRMETHOD、TREVAL                       |                                                                                                                 |
+----------------------------------------+-----------------------------------------------------------------------------------------------------------------+
| ANADIR                                 | 分析用先前最小直径和                                                                                            |
+----------------------------------------+-----------------------------------------------------------------------------------------------------------------+
| NADIRCHG                               | 相对最小直径和变化值                                                                                            |
+----------------------------------------+-----------------------------------------------------------------------------------------------------------------+
| PCNSD                                  | 相对最小直径和变化百分比                                                                                        |
+----------------------------------------+-----------------------------------------------------------------------------------------------------------------+

``` note
需要注意的是，除了EDC中直接收集的靶病灶直径和外，在ADTR中我们还会额外编程衍生"分析用靶病灶直径和"。程序员在编程时，最好核对下直接收集的和程序衍生的靶病灶直径和结果是否一致。
```