---
title: "无进展生存期(PFS)"
---

# 1 无进展生存期

**无进展生存期(Progression-Free Survival, PFS)**是指从治疗开始到有记录的疾病进展（符合RECIST 1.1）或任何原因导致的死亡（以先发生者为准）的时间。

::: callout-note
治疗开始日期通常指随机化日期或给药开始日期，具体定义应在统计分析计划中明确。
:::

**有效的总体评估日期**：总体疗效评估结果为CR,PR,SD或Non-CR/Non-PD的[**总体评估日期**](oncology.qmd#date-of-response)。NE或未查的评估日期将不会被用作为事件/删失日期。PFS时间将始终基于有效的总体评估日期。

## 1.1 PFS事件的定义

PFS事件只包含疾病进展和死亡。疾病进展和死亡发生在上次有效肿瘤评估/治疗开始日期xx天内才能被定义为PFS事件。xx通常为2个肿瘤评估间隔。

## 1.2 PFS删失

受试者没有发生疾病进展或死亡，或疾病进展或死亡发生在上次有效肿瘤评估/治疗开始日期xx天后，PFS时间将被删失。删失日期为疾病进展或死亡前的最后一次有效的肿瘤评估日期。此外，若受试者在PFS事件前发生新抗肿瘤治疗，删失日期为新抗肿瘤治疗前末次有效的肿瘤评估日期/治疗开始日期。

对于没有有效的基线或基线后肿瘤评估的受试者，会判为删失，删失日期为治疗开始日期。除非受试者在治疗开始后xx天内死亡，在这种情况下，死亡将作为事件，发生日期记为死亡日期。xx通常为2个肿瘤评估周期。

## 1.2.1 PFS的删失准则

| 情况 | 进展或删失日期 | 结果 |
|---------------------------|----------------------------|------------------|
| 无基线或基线后有效肿评，并且治疗开始xx天内未出现死亡 | 随机/给药日期 | 删失 |
| 无基线或基线后有效肿评，并且治疗开始xx天内出现死亡 | 死亡日期 | 事件 |
| 疾病进展或死亡发生在上次有效肿瘤评估/治疗开始日期xx天内 | 进展或死亡日期 | 事件 |
| 疾病进展或死亡发生在上次有效肿瘤评估/治疗开始日期xx天后[^1] | 在进展（或死亡）日期之前最后一次有效的肿瘤评估日期 | 删失 |
| 受试者在PFS事件前发生新抗肿瘤治疗[^2] | 在进展（或死亡）日期之前最后一次有效的肿瘤评估日期/治疗开始日期 | 删失 |
| 数据截止或退出研究或失访前未发生疾病进展、死亡和新抗 | 最后一次有效的肿瘤评估日期 | 删失 |

[^1]: xx天通常为2个肿瘤评估间隔。但由于肿瘤评估间隔可能是不固定的，比如前24周每6周评估一次，之后每9周评估一次。因此xx天就不在是固定的某个数值了（详见下）。

[^2]: 如果PD或死亡与开始新的抗肿瘤治疗发生在同一天，则假定疾病进展或死亡先发生（即结局为疾病进展或死亡，日期为评估疾病进展日期或死亡日期）。

## 1.2.2 肿评间隔的xx天分类讨论 {#pfs-rs2dur}

### 1.2.2.1 固定肿评间隔

若方案设计中肿瘤评估间隔的设计是固定的，如一直都是每6周（±7）天进行一次疗效评估，那么xx天就通常为6周\*7+时间窗。

### 1.2.2.2 非固定肿评间隔

若方案设计中肿瘤评估间隔不是固定的，如[肿瘤评估流程：前24周每6周（±7天）进行一次影像学疗效评估，24周后每9周（±7天）进行一次影像学疗效评估。]{.mark}那么xx天的确定就需要分类讨论。

具体的思路：按照事件发生前的末次肿评日期距离治疗开始日期的时间间隔，来确定受试者在该时间点所处的肿评周期，从而匹配对应的计划肿瘤评估频率。

**类别1（无基线后有效肿评/首次肿评发生PD）**

| 时间窗（Y） | 两次肿评间隔天数（X） | xx天 |
|------------------------|------------------------|------------------------|
| 无基线后有效肿评/首次肿评发生PD | X = 疾病进展或死亡日期 - 治疗开始日期 |  |
| 无 | X \> 91 | xx = 91 |

**类别2（PD或死亡前存在一次或以上有效肿评）**

| 时间窗（Y） | 两次肿评间隔天数（X） | xx天 |
|------------------------|------------------------|------------------------|
| Y = 疾病进展或死亡前最后一次有效的影像学检查日期 - 治疗开始日期 | X = 疾病进展或死亡日期-疾病进展或死亡前最后一次有效的影像学检查日期 |  |
| 0 \< Y ≤105（第12周及之前，12×7+21） | X \> 98（6×7+7+6×7+7） | xx = 98 |
| 105 \< Y ≤147（12周后-18周，18×7+21） | X \> 119（6×7+7+9×7+7） | xx = 119 |
| 147 \< Y（18周之后，18×7+21） | X \> 140（9×7+7+9×7+7） | xx = 140 |

## 1.3 PFS删失原因

| 序号 | 删失原因                  |
|------|---------------------------|
| 1    | 无基线或基线后评估        |
| 2    | 开始新抗肿瘤治疗          |
| 3    | 连续2次肿评缺失后发生事件 |
| 4    | 继续试验，无事发生        |
| 5    | 失访/撤回知情同意/其他    |